### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by Razdeep** [Razdeep/splitwebp#3]
Using google-test write unit tests for the project.
The GTest project should be built as an `ExternalProject` in cmake.
Do not add GTest as a submodule or insert the project files directly.

**Comment by ollelogdahl** [comment]
Hello. I want to contribute to this! :) Working on it now

**Comment by Razdeep** [comment]
Great!
GTest should be downloaded & built once if a flag like `-DBUILD_TEST=ON` is provided along with the CMake command.

**Comment by ollelogdahl** [comment]
Having some problems compiling the source. `splitwebp.cpp` requires `fstream` (`std::fstream` is defined in `fstream`). I will replace the `iostream` include for the `fstream`, since `fstream` itself includes `iostream`. Linux also requires hdl5 installed separately (dependency of libopencv_hdl), and therefore i have added it in the dependency list in README. I will add this in my final commit :)

**Comment by ollelogdahl** [comment]
Im still intrested in making actual tests for the project, if someone else has the experience to set up the correct environment.

**Comment by Razdeep** [comment]
Did you manage to compile the source on Linux? What distribution are you using? And what is the opencv version that you have downloaded?

For now, you can install GTest globally (using a package manager like apt-get), and write the tests. Later on, we'll figure out a way to use GTest as `ExternalProject`.

**Comment by ollelogdahl** [comment]
Using Archlinux. It compiled sucessfully, once i manually installed hdl5 and fixed the include error. Using openCV 4.4.
I will go ahead and write some tests, compiling them globally.
